-- ============================================================
-- PIXELSTORE (tech-store) : Schéma Supabase / PostgreSQL
-- Site e-commerce de matériel informatique (BIF - Francs burundais)
-- Flux complet : users (admin + users), catalogue, stock, commandes
--
-- NOUVELLE STRUCTURE (mise à jour — correspond au projet actuel) :
--   * Produits « maison » PixelStore (brand = PixelStore)
--   * tag (badge marché) au lieu d'une catégorie obligatoire
--   * stock = QUANTITÉ entière (pas un booléen)
--   * gallery = plusieurs images par produit
--   * specs = caractéristiques techniques (label/valeur)
--   * cert = certificat de conformité
--   * warranty = garantie
--
-- À exécuter dans le SQL Editor de Supabase.
-- L'utilisateur est géré par Supabase Auth (auth.users), référencé
-- via auth.uid() dans la RLS.
-- ============================================================

-- Extension pour générer des UUID
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Helper : l'utilisateur courant est-il admin ?
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- ============================================================
-- 1. GESTION DES UTILISATEURS
-- ============================================================

-- Profil utilisateur relié à auth.users (Supabase Auth)
CREATE TABLE IF NOT EXISTS public.users (
  id         uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name text,
  last_name  text,
  email      text UNIQUE,
  phone      text,
  role       text NOT NULL DEFAULT 'user' CHECK (role IN ('admin','user')),
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.users IS 'Profil utilisateur synchronisé avec Supabase Auth';

-- Trigger : profil auto-créé à l'inscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.users (id, email, first_name, last_name)
  VALUES (NEW.id, NEW.email, coalesce(NEW.raw_user_meta_data->>'first_name',''),
          coalesce(NEW.raw_user_meta_data->>'last_name',''));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.handle_user_update()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.users SET email = NEW.email, updated_at = now()
  WHERE id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
  AFTER UPDATE OF email ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_user_update();

-- Adresses
CREATE TABLE IF NOT EXISTS public.addresses (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  address_line1 text NOT NULL,
  address_line2 text,
  city          text NOT NULL,                    -- ex: Bujumbura
  province      text,
  country       text NOT NULL DEFAULT 'Burundi',
  phone         text,
  is_default    boolean NOT NULL DEFAULT false,
  type          text NOT NULL DEFAULT 'shipping' CHECK (type IN ('shipping','billing')),
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 2. CATALOGUE PRODUITS (nouvelle structure)
-- ============================================================

-- Catégories (optionnelles, pour filtrer le catalogue)
CREATE TABLE IF NOT EXISTS public.categories (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  slug       text NOT NULL UNIQUE,
  parent_id  bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Marques (PixelStore + partenaires)
CREATE TABLE IF NOT EXISTS public.brands (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  slug       text NOT NULL UNIQUE,
  logo_url   text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Produits — alignés sur data.js (pixelProducts) et products.js (catalogue)
CREATE TABLE IF NOT EXISTS public.products (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  slug         text NOT NULL UNIQUE,
  reference    text NOT NULL UNIQUE,          -- SKU (ex: ORD-PX-X15)
  category_id  bigint REFERENCES public.categories(id) ON DELETE SET NULL, -- nullable
  brand_id     bigint REFERENCES public.brands(id) ON DELETE SET NULL,
  tag          text,                          -- badge marché ("Nouveau","Top vente"...)
  description  text,                          -- desc
  price        numeric(12,2) NOT NULL CHECK (price >= 0),   -- BIF
  old_price    numeric(12,2) CHECK (old_price IS NULL OR old_price >= 0),
  rating       numeric(3,1) NOT NULL DEFAULT 0,
  rating_count integer NOT NULL DEFAULT 0,
  warranty     text,                          -- garantie ("2 ans")
  is_active    boolean NOT NULL DEFAULT true,
  is_featured  boolean NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand    ON public.products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_price    ON public.products(price);
CREATE INDEX IF NOT EXISTS idx_products_active   ON public.products(is_active);

-- Galerie d'images (correspond à product.gallery[])
CREATE TABLE IF NOT EXISTS public.product_images (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  image_url  text NOT NULL,                    -- ex: img/products/xxxx.jpg
  alt_text   text,
  sort_order integer NOT NULL DEFAULT 0,       -- 0 = image principale
  is_main    boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_pimages_product ON public.product_images(product_id);

-- Caractéristiques techniques (correspond à product.specs [[label,value],...])
CREATE TABLE IF NOT EXISTS public.product_specs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  label      text NOT NULL,                    -- ex: "Processeur"
  value      text NOT NULL,                    -- ex: "Intel Core i7-13700H"
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT uq_spec UNIQUE (product_id, label)
);
CREATE INDEX IF NOT EXISTS idx_specs_product ON public.product_specs(product_id);

-- Certificat de conformité (correspond à product.cert)
CREATE TABLE IF NOT EXISTS public.product_certificates (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL UNIQUE REFERENCES public.products(id) ON DELETE CASCADE,
  title      text NOT NULL,                    -- "Certificat de conformité CE"
  number     text,                             -- "PC-2026-0015"
  authority  text,                             -- "Bureau Burundais de Normalisation (BBN)"
  cert_date  date,                             -- "12/06/2026"
  points     jsonb NOT NULL DEFAULT '[]'::jsonb  -- liste de points de conformité
);

-- ============================================================
-- 3. GESTION DES STOCKS (quantité entière)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.stock (
  product_id          bigint PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
  quantity            integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),   -- ex: 8
  reserved_quantity   integer NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
  low_stock_threshold integer NOT NULL DEFAULT 5,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stock_movements (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id       uuid REFERENCES public.users(id) ON DELETE SET NULL,
  quantity      integer NOT NULL,               -- >0 entrée, <0 sortie
  movement_type text NOT NULL CHECK (movement_type IN ('purchase','sale','return','adjustment','restock')),
  reference     text,
  note          text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sm_product ON public.stock_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_sm_created ON public.stock_movements(created_at);

-- ============================================================
-- 4. PANIER & CODES PROMO
-- ============================================================

CREATE TABLE IF NOT EXISTS public.carts (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cart_items (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id    uuid NOT NULL REFERENCES public.carts(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity   integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  added_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (cart_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.coupons (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code             text NOT NULL UNIQUE,
  discount_type    text NOT NULL DEFAULT 'percentage' CHECK (discount_type IN ('percentage','fixed')),
  discount_value   numeric(12,2) NOT NULL,
  min_order_amount numeric(12,2),
  max_uses         integer,
  times_used       integer NOT NULL DEFAULT 0,
  starts_at        timestamptz,
  expires_at       timestamptz,
  is_active        boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.wishlists (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, product_id)
);

-- ============================================================
-- 5. COMMANDES & PAIEMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.orders (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number        text NOT NULL UNIQUE,      -- ex: PS-20260829-00001
  user_id             uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  coupon_id           bigint REFERENCES public.coupons(id) ON DELETE SET NULL,
  status              text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','confirmed','processing','shipped','delivered','cancelled','refunded')),
  payment_status      text NOT NULL DEFAULT 'pending'
                      CHECK (payment_status IN ('pending','paid','failed','refunded')),
  payment_method      text CHECK (payment_method IN ('card','paypal','cod','bank_transfer','mobile_money')),
  shipping_address_id uuid REFERENCES public.addresses(id) ON DELETE SET NULL,
  billing_address_id  uuid REFERENCES public.addresses(id) ON DELETE SET NULL,
  subtotal            numeric(12,2) NOT NULL DEFAULT 0,
  discount_total      numeric(12,2) NOT NULL DEFAULT 0,
  shipping_cost       numeric(12,2) NOT NULL DEFAULT 5000,
  tax_total           numeric(12,2) NOT NULL DEFAULT 0,
  grand_total         numeric(12,2) NOT NULL DEFAULT 0,
  customer_notes      text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_orders_user    ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status  ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON public.orders(created_at);

CREATE TABLE IF NOT EXISTS public.order_items (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id      bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  product_name    text NOT NULL,
  quantity        integer NOT NULL CHECK (quantity > 0),
  unit_price      numeric(12,2) NOT NULL,
  discount_amount numeric(12,2) NOT NULL DEFAULT 0,
  subtotal        numeric(12,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_oi_order   ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_oi_product ON public.order_items(product_id);

CREATE TABLE IF NOT EXISTS public.order_status_history (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  status     text NOT NULL
             CHECK (status IN ('pending','confirmed','processing','shipped','delivered','cancelled','refunded')),
  changed_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_osh_order ON public.order_status_history(order_id);

CREATE TABLE IF NOT EXISTS public.payments (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  transaction_id text,
  amount         numeric(12,2) NOT NULL,
  currency       text NOT NULL DEFAULT 'BIF',
  status         text NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','success','failed','cancelled','refunded')),
  gateway        text,
  paid_at        timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pay_order ON public.payments(order_id);

CREATE TABLE IF NOT EXISTS public.reviews (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  rating      smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title       text,
  comment     text,
  is_approved boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (product_id, user_id)
);

-- ============================================================
-- VUES UTILES (dashboards admin)
-- ============================================================

-- Produits disponibles (stock réel > 0), avec image principale, tag, prix
CREATE OR REPLACE VIEW public.v_products_available AS
SELECT p.id, p.name, p.slug, p.reference, p.tag, p.price, p.old_price,
       p.rating, p.warranty, c.name AS category, b.name AS brand,
       (s.quantity - s.reserved_quantity) AS available_qty,
       pi.image_url AS main_image
FROM public.products p
LEFT JOIN public.categories c ON c.id = p.category_id
LEFT JOIN public.brands b ON b.id = p.brand_id
LEFT JOIN public.stock s ON s.product_id = p.id
LEFT JOIN LATERAL (
  SELECT image_url FROM public.product_images
  WHERE product_id = p.id ORDER BY sort_order LIMIT 1
) pi ON true
WHERE p.is_active AND (s.quantity - s.reserved_quantity) > 0;

-- Alerte stock faible / rupture
CREATE OR REPLACE VIEW public.v_low_stock AS
SELECT p.id, p.name, p.reference, s.quantity, s.reserved_quantity,
       (s.quantity - s.reserved_quantity) AS available,
       s.low_stock_threshold
FROM public.products p
JOIN public.stock s ON s.product_id = p.id
WHERE (s.quantity - s.reserved_quantity) <= s.low_stock_threshold;

-- Résumé des commandes par statut
CREATE OR REPLACE VIEW public.v_order_summary AS
SELECT status, COUNT(*) AS order_count, COALESCE(SUM(grand_total),0) AS total_amount
FROM public.orders
GROUP BY status;

-- Chiffre d'affaires total
CREATE OR REPLACE VIEW public.v_revenue AS
SELECT COALESCE(SUM(grand_total),0) AS total_revenue,
       COUNT(*) AS total_orders
FROM public.orders
WHERE status NOT IN ('cancelled','refunded');

-- Fiche produit complète (galerie, specs, certificat) pour produit.html
CREATE OR REPLACE VIEW public.v_product_full AS
SELECT p.*,
       c.name AS category, b.name AS brand,
       COALESCE(
         (SELECT jsonb_agg(jsonb_build_object('label',s.label,'value',s.value) ORDER BY s.sort_order)
          FROM public.product_specs s WHERE s.product_id = p.id), '[]'::jsonb) AS specs,
       COALESCE(
         (SELECT jsonb_agg(image_url ORDER BY sort_order)
          FROM public.product_images WHERE product_id = p.id), '[]'::jsonb) AS gallery,
       (SELECT jsonb_build_object('title', title, 'number', number, 'authority', authority,
                                 'cert_date', cert_date, 'points', points)
        FROM public.product_certificates c2 WHERE c2.product_id = p.id) AS cert,
       (SELECT quantity FROM public.stock WHERE product_id = p.id) AS stock
FROM public.products p
LEFT JOIN public.categories c ON c.id = p.category_id
LEFT JOIN public.brands b ON b.id = p.brand_id;

-- ============================================================
-- FONCTION : créer une commande (décrémente le stock)
-- ============================================================
CREATE OR REPLACE FUNCTION public.create_order(
  p_payment_method text,
  p_coupon_code text DEFAULT NULL,
  p_shipping_address_id uuid DEFAULT NULL,
  p_billing_address_id uuid DEFAULT NULL
)
RETURNS TABLE(order_id uuid, subtotal numeric, discount_total numeric, grand_total numeric)
LANGUAGE plpgsql
AS $$
DECLARE
  v_cart_id        uuid;
  v_order_id       uuid;
  v_subtotal       numeric(12,2) := 0;
  v_discount       numeric(12,2) := 0;
  v_coupon_id      bigint;
  v_item           record;
  v_avail          integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Utilisateur non authentifié';
  END IF;

  SELECT id INTO v_cart_id FROM public.carts WHERE user_id = auth.uid();
  IF v_cart_id IS NULL THEN
    RAISE EXCEPTION 'Panier vide ou introuvable';
  END IF;

  IF p_coupon_code IS NOT NULL THEN
    SELECT ci.id, ci.discount_value
      INTO v_coupon_id, v_discount
    FROM public.coupons ci
    WHERE ci.code = p_coupon_code AND ci.is_active
      AND (ci.expires_at IS NULL OR ci.expires_at > now())
    LIMIT 1;
  END IF;

  INSERT INTO public.orders (order_number, user_id, coupon_id, payment_method,
                             shipping_address_id, billing_address_id)
  VALUES ('PS-' || to_char(now(),'YYYYMMDD') || '-' ||
          lpad((floor(random()*99999))::text, 5, '0'),
          auth.uid(), v_coupon_id, p_payment_method,
          p_shipping_address_id, p_billing_address_id)
  RETURNING id INTO v_order_id;

  FOR v_item IN
    SELECT ci.product_id, ci.quantity, p.price
    FROM public.cart_items ci
    JOIN public.products p ON p.id = ci.product_id
    WHERE ci.cart_id = v_cart_id
  LOOP
    SELECT (quantity - reserved_quantity) INTO v_avail
    FROM public.stock WHERE product_id = v_item.product_id;

    IF v_avail IS NULL OR v_avail < v_item.quantity THEN
      RAISE EXCEPTION 'Stock insuffisant pour le produit %', v_item.product_id;
    END IF;

    INSERT INTO public.order_items (order_id, product_id, product_name, quantity,
                                    unit_price, subtotal)
    SELECT v_order_id, p.id, p.name, v_item.quantity, p.price, p.price * v_item.quantity
    FROM public.products p WHERE p.id = v_item.product_id;

    UPDATE public.stock SET quantity = quantity - v_item.quantity
    WHERE product_id = v_item.product_id;

    INSERT INTO public.stock_movements (product_id, user_id, quantity, movement_type, reference)
    VALUES (v_item.product_id, auth.uid(), -v_item.quantity, 'sale', v_order_id::text);

    v_subtotal := v_subtotal + (v_item.price * v_item.quantity);
  END LOOP;

  IF v_coupon_id IS NOT NULL AND v_discount > v_subtotal THEN
    v_discount := v_subtotal;
  END IF;

  UPDATE public.orders
  SET subtotal = v_subtotal,
      discount_total = v_discount,
      shipping_cost = 5000,
      grand_total = v_subtotal - v_discount + 5000
  WHERE id = v_order_id;

  INSERT INTO public.order_status_history (order_id, status, changed_by, note)
  VALUES (v_order_id, 'pending', auth.uid(), 'Commande créée');

  IF v_coupon_id IS NOT NULL THEN
    UPDATE public.coupons SET times_used = times_used + 1 WHERE id = v_coupon_id;
  END IF;

  DELETE FROM public.cart_items WHERE cart_id = v_cart_id;

  RETURN QUERY SELECT v_order_id, v_subtotal, v_discount, v_subtotal - v_discount + 5000;
END;
$$;

-- ============================================================
-- SÉCURITÉ AU NIVEAU DES LIGNES (RLS)
-- ============================================================
ALTER TABLE public.users        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_specs  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_self ON public.users
  FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());

CREATE POLICY addresses_self ON public.addresses
  FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY carts_self ON public.carts
  FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY cart_items_self ON public.cart_items
  FOR ALL USING (cart_id IN (SELECT id FROM public.carts WHERE user_id = auth.uid()))
  WITH CHECK (cart_id IN (SELECT id FROM public.carts WHERE user_id = auth.uid()));

CREATE POLICY wishlists_self ON public.wishlists
  FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY orders_self ON public.orders
  FOR SELECT USING (user_id = auth.uid() OR public.is_admin());
CREATE POLICY orders_insert ON public.orders
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY order_items_self ON public.order_items
  FOR SELECT USING (order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid() OR public.is_admin()));

CREATE POLICY payments_self ON public.payments
  FOR SELECT USING (order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid() OR public.is_admin()));

CREATE POLICY reviews_read ON public.reviews FOR SELECT USING (true);
CREATE POLICY reviews_insert ON public.reviews FOR INSERT
  WITH CHECK (user_id = auth.uid());

CREATE POLICY products_read   ON public.products   FOR SELECT USING (is_active);
CREATE POLICY products_write  ON public.products   FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY pimages_read  ON public.product_images FOR SELECT USING (true);
CREATE POLICY pimages_write ON public.product_images FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY specs_read  ON public.product_specs FOR SELECT USING (true);
CREATE POLICY specs_write ON public.product_specs FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY cert_read  ON public.product_certificates FOR SELECT USING (true);
CREATE POLICY cert_write ON public.product_certificates FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY categories_read ON public.categories FOR SELECT USING (true);
CREATE POLICY categories_write ON public.categories FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY brands_read ON public.brands FOR SELECT USING (true);
CREATE POLICY brands_write ON public.brands FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY stock_read  ON public.stock FOR SELECT USING (true);
CREATE POLICY stock_write ON public.stock FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY sm_read  ON public.stock_movements FOR SELECT USING (public.is_admin());
CREATE POLICY sm_write ON public.stock_movements FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY coupons_read ON public.coupons FOR SELECT USING (is_active);
CREATE POLICY coupons_write ON public.coupons FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY osh_read ON public.order_status_history FOR SELECT
  USING (order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid() OR public.is_admin()));

-- ============================================================
-- DONNÉES DE DÉMONSTRATION (alignées sur data.js + products.js)
-- ============================================================

-- Marques
INSERT INTO public.brands (name, slug) VALUES
('PixelStore','pixelstore'),('Dell','dell'),('HP','hp'),('Logitech','logitech'),
('Razer','razer'),('Samsung','samsung'),('Sony','sony')
ON CONFLICT (slug) DO NOTHING;

-- Catégories (catalogue frontend)
INSERT INTO public.categories (name, slug) VALUES
('Ordinateurs','ordinateurs'),('Claviers','claviers'),('Souris','souris'),
('Écrans','ecrans'),('Casques','casques'),('Composants','composants')
ON CONFLICT (slug) DO NOTHING;

-- Produits « maison » PixelStore (data.js, ids 1-12)
INSERT INTO public.products
  (id, name, slug, reference, brand_id, tag, description, price, old_price, rating, rating_count, warranty)
SELECT d.id, d.name, d.slug, d.reference, b.id, d.tag, d.desc, d.price, d.old_price, d.rating, d.rating_count, d.warranty
FROM (VALUES
  (1::bigint,'OrdiPro Pixel X15','ordipro-pixel-x15','ORD-PX-X15','PixelStore','Nouveau',
   'L''ultrabook signature de PixelStore : puissance, finesse et autonomie.',850000.00,950000.00,4.8::numeric,1,'2 ans'),
  (2,'Clavier MécaK Pixel K68','clavier-mecak-pixel-k68','CLV-K68-RGB','PixelStore','Top vente',
   'Un clavier mécanique compact aux switchs tactiles.',65000.00,85000.00,4.7,1,'1 an'),
  (3,'PixelMouse Pro','pixelmouse-pro','SOU-PX-PRO','PixelStore','Nouveau',
   'Notre souris gaming référence : capteur haute précision.',45000.00,58000.00,4.6,1,'2 ans'),
  (4,'Écran UltraPixel 27''''','ecran-ultrapixel-27','ECR-UP-27K','PixelStore','4K Ultra HD',
   'Un moniteur 4K aux couleurs ultra-fidèles.',320000.00,380000.00,4.9,1,'2 ans'),
  (5,'Casque PixelSound H90','casque-pixelsound-h90','CSQ-PS-H90','PixelStore','Son immersif',
   'Un casque surround à réduction de bruit active.',95000.00,110000.00,4.7,1,'1 an'),
  (6,'SSD PixelStore 1To NVMe','ssd-pixelstore-1to-nvme','SSD-PX-1TB','PixelStore','Performance',
   'Un SSD ultra-rapide pour des chargements instantanés.',55000.00,65000.00,4.8,1,'5 ans'),
  (7,'PixelBook 14','pixelbook-14','PC-PB-14','PixelStore','Ultra mobile',
   'Un ultrabook léger et endurant, pensé pour la mobilité.',720000.00,800000.00,4.6,1,'2 ans'),
  (8,'Clavier PixelK Air 75','clavier-pixelk-air-75','CLV-K75-AIR','PixelStore','Confort',
   'Un clavier compact 75% au châssis fin.',78000.00,90000.00,4.5,1,'1 an'),
  (9,'Souris PixelEase','souris-pixelease','SOU-PX-EASE','PixelStore','Confort',
   'Une souris silencieuse et légère pour un confort durable.',28000.00,35000.00,4.4,1,'1 an'),
  (10,'Écran VisionPixel 24''''','ecran-visionpixel-24','ECR-VP-24F','PixelStore','Essentiel',
   'Un écran FHD polyvalent au suivi fluide.',145000.00,175000.00,4.5,1,'2 ans'),
  (11,'Casque PixelStudio','casque-pixelstudio','CSQ-PS-STUDIO','PixelStore','Créateurs',
   'Un casque Hi-Fi à réduction de bruit hybride.',120000.00,140000.00,4.8,1,'2 ans'),
  (12,'PixelGPU RTX 4070','pixelgpu-rtx-4070','GPU-PX-4070','PixelStore','Puissance',
   'La carte graphique nouvelle génération pour du gaming 1440p-4K.',620000.00,680000.00,4.9,1,'3 ans')
) AS d(id, name, slug, reference, brand_name, tag, desc, price, old_price, rating, rating_count, warranty)
JOIN public.brands b ON b.name = d.brand_name
ON CONFLICT (id) DO NOTHING;

-- Stocks (alignés sur data.js : stock des produits PixelStore)
INSERT INTO public.stock (product_id, quantity, low_stock_threshold)
SELECT p.id, sv.qty, 5
FROM (VALUES
  (1::bigint,8),(2,15),(3,20),(4,6),(5,12),(6,30),
  (7,10),(8,22),(9,18),(10,14),(11,7),(12,4)
) AS sv(pid, qty)
JOIN public.products p ON p.id = sv.pid
ON CONFLICT (product_id) DO NOTHING;

-- Coupon de démo
INSERT INTO public.coupons (code, discount_type, discount_value, is_active)
VALUES ('BIENVENUE10', 'percentage', 10, true)
ON CONFLICT (code) DO NOTHING;
