-- ============================================================
-- PIXELSTORE (tech-store) : Schéma Supabase / PostgreSQL
-- Site e-commerce de matériel informatique (BIF - Francs burundais)
-- Flux complet : users (admin + users), catalogue, stock, commandes
--
-- NOUVELLE STRUCTURE (mise à jour — correspond au projet actuel) :
--   * Produits « maison » PixelStore (brand = PixelStore)
--   * tag (badge marché) au lieu d'une catégorie obligatoire
--   * stock = QUANTITÉ entière (pas un booléen)
--   * gallery = plusieurs images par produit
--   * specs = caractéristiques techniques (label/valeur)
--   * cert = certificat de conformité
--   * warranty = garantie
--
-- À exécuter dans le SQL Editor de Supabase.
-- L'utilisateur est géré par Supabase Auth (auth.users), référencé
-- via auth.uid() dans la RLS.
-- ============================================================

-- Extension pour générer des UUID
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. GESTION DES UTILISATEURS
-- ============================================================

-- Profil utilisateur relié à auth.users (Supabase Auth)
CREATE TABLE IF NOT EXISTS public.users (
  id         uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name text,
  last_name  text,
  email      text UNIQUE,
  phone      text,
  role       text NOT NULL DEFAULT 'user' CHECK (role IN ('admin','user')),
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.users IS 'Profil utilisateur synchronisé avec Supabase Auth';

-- Trigger : profil auto-créé à l'inscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- L'email administrateur fixe devient automatiquement admin.
  INSERT INTO public.users (id, email, first_name, last_name, role)
  SELECT NEW.id, NEW.email,
         coalesce(NULLIF(NEW.raw_user_meta_data->>'first_name',''),
                  NULLIF(split_part(coalesce(NEW.raw_user_meta_data->>'full_name',''), ' ', 1), ''),
                  ''),
         coalesce(NULLIF(NEW.raw_user_meta_data->>'last_name',''),
                  CASE WHEN position(' ' in coalesce(NEW.raw_user_meta_data->>'full_name','')) > 0
                       THEN substr(coalesce(NEW.raw_user_meta_data->>'full_name',''),
                                   position(' ' in coalesce(NEW.raw_user_meta_data->>'full_name','')) + 1)
                       ELSE '' END,
                  ''),
         CASE WHEN lower(NEW.email) = lower('admin@pixelstore.bi') THEN 'admin'::text ELSE 'user'::text END;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.handle_user_update()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.users
     SET email = NEW.email,
         role = CASE WHEN lower(NEW.email) = lower('admin@pixelstore.bi')
                     THEN 'admin'::text ELSE role END,
         updated_at = now()
   WHERE id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
  AFTER UPDATE OF email ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_user_update();

-- Helper : l'utilisateur courant est-il admin ?
-- (défini ici, après la création de public.users qu'il référence)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- Adresses
CREATE TABLE IF NOT EXISTS public.addresses (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  address_line1 text NOT NULL,
  address_line2 text,
  city          text NOT NULL,                    -- ex: Bujumbura
  province      text,
  country       text NOT NULL DEFAULT 'Burundi',
  phone         text,
  is_default    boolean NOT NULL DEFAULT false,
  type          text NOT NULL DEFAULT 'shipping' CHECK (type IN ('shipping','billing')),
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 2. CATALOGUE PRODUITS (nouvelle structure)
-- ============================================================

-- Catégories (optionnelles, pour filtrer le catalogue)
CREATE TABLE IF NOT EXISTS public.categories (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  slug       text NOT NULL UNIQUE,
  parent_id  bigint REFERENCES public.categories(id) ON DELETE SET NULL,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Marques (PixelStore + partenaires)
CREATE TABLE IF NOT EXISTS public.brands (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  slug       text NOT NULL UNIQUE,
  logo_url   text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Produits — alignés sur data.js (pixelProducts) et products.js (catalogue)
CREATE TABLE IF NOT EXISTS public.products (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  slug         text NOT NULL UNIQUE,
  reference    text NOT NULL UNIQUE,          -- SKU (ex: ORD-PX-X15)
  category_id  bigint REFERENCES public.categories(id) ON DELETE SET NULL, -- nullable
  brand_id     bigint REFERENCES public.brands(id) ON DELETE SET NULL,
  tag          text,                          -- badge marché ("Nouveau","Top vente"...)
  description  text,                          -- desc
  price        numeric(12,2) NOT NULL CHECK (price >= 0),   -- BIF
  old_price    numeric(12,2) CHECK (old_price IS NULL OR old_price >= 0),
  rating       numeric(3,1) NOT NULL DEFAULT 0,
  rating_count integer NOT NULL DEFAULT 0,
  warranty     text,                          -- garantie ("2 ans")
  is_active    boolean NOT NULL DEFAULT true,
  is_featured  boolean NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand    ON public.products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_price    ON public.products(price);
CREATE INDEX IF NOT EXISTS idx_products_active   ON public.products(is_active);

-- Galerie d'images (correspond à product.gallery[])
CREATE TABLE IF NOT EXISTS public.product_images (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  image_url  text NOT NULL,                    -- ex: img/products/xxxx.jpg
  alt_text   text,
  sort_order integer NOT NULL DEFAULT 0,       -- 0 = image principale
  is_main    boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_pimages_product ON public.product_images(product_id);

-- Caractéristiques techniques (correspond à product.specs [[label,value],...])
CREATE TABLE IF NOT EXISTS public.product_specs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  label      text NOT NULL,                    -- ex: "Processeur"
  value      text NOT NULL,                    -- ex: "Intel Core i7-13700H"
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT uq_spec UNIQUE (product_id, label)
);
CREATE INDEX IF NOT EXISTS idx_specs_product ON public.product_specs(product_id);

-- Certificat de conformité (correspond à product.cert)
CREATE TABLE IF NOT EXISTS public.product_certificates (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL UNIQUE REFERENCES public.products(id) ON DELETE CASCADE,
  title      text NOT NULL,                    -- "Certificat de conformité CE"
  number     text,                             -- "PC-2026-0015"
  authority  text,                             -- "Bureau Burundais de Normalisation (BBN)"
  cert_date  date,                             -- "12/06/2026"
  points     jsonb NOT NULL DEFAULT '[]'::jsonb  -- liste de points de conformité
);

-- ============================================================
-- 3. GESTION DES STOCKS (quantité entière)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.stock (
  product_id          bigint PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
  quantity            integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),   -- ex: 8
  reserved_quantity   integer NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
  low_stock_threshold integer NOT NULL DEFAULT 5,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stock_movements (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id       uuid REFERENCES public.users(id) ON DELETE SET NULL,
  quantity      integer NOT NULL,               -- >0 entrée, <0 sortie
  movement_type text NOT NULL CHECK (movement_type IN ('purchase','sale','return','adjustment','restock')),
  reference     text,
  note          text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sm_product ON public.stock_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_sm_created ON public.stock_movements(created_at);

-- ============================================================
-- 4. PANIER & CODES PROMO
-- ============================================================

CREATE TABLE IF NOT EXISTS public.carts (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cart_items (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id    uuid NOT NULL REFERENCES public.carts(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity   integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  added_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (cart_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.coupons (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code             text NOT NULL UNIQUE,
  discount_type    text NOT NULL DEFAULT 'percentage' CHECK (discount_type IN ('percentage','fixed')),
  discount_value   numeric(12,2) NOT NULL,
  min_order_amount numeric(12,2),
  max_uses         integer,
  times_used       integer NOT NULL DEFAULT 0,
  starts_at        timestamptz,
  expires_at       timestamptz,
  is_active        boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.wishlists (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, product_id)
);

-- ============================================================
-- 5. COMMANDES & PAIEMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.orders (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number        text NOT NULL UNIQUE,      -- ex: PS-20260829-00001
  user_id             uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  coupon_id           bigint REFERENCES public.coupons(id) ON DELETE SET NULL,
  status              text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','confirmed','processing','shipped','delivered','cancelled','refunded')),
  payment_status      text NOT NULL DEFAULT 'pending'
                      CHECK (payment_status IN ('pending','paid','failed','refunded')),
  payment_method      text CHECK (payment_method IN ('card','paypal','cod','bank_transfer','mobile_money')),
  shipping_address_id uuid REFERENCES public.addresses(id) ON DELETE SET NULL,
  billing_address_id  uuid REFERENCES public.addresses(id) ON DELETE SET NULL,
  subtotal            numeric(12,2) NOT NULL DEFAULT 0,
  discount_total      numeric(12,2) NOT NULL DEFAULT 0,
  shipping_cost       numeric(12,2) NOT NULL DEFAULT 5000,
  tax_total           numeric(12,2) NOT NULL DEFAULT 0,
  grand_total         numeric(12,2) NOT NULL DEFAULT 0,
  customer_notes      text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_orders_user    ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status  ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON public.orders(created_at);

CREATE TABLE IF NOT EXISTS public.order_items (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id      bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  product_name    text NOT NULL,
  quantity        integer NOT NULL CHECK (quantity > 0),
  unit_price      numeric(12,2) NOT NULL,
  discount_amount numeric(12,2) NOT NULL DEFAULT 0,
  subtotal        numeric(12,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_oi_order   ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_oi_product ON public.order_items(product_id);

CREATE TABLE IF NOT EXISTS public.order_status_history (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  status     text NOT NULL
             CHECK (status IN ('pending','confirmed','processing','shipped','delivered','cancelled','refunded')),
  changed_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_osh_order ON public.order_status_history(order_id);

CREATE TABLE IF NOT EXISTS public.payments (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  transaction_id text,
  amount         numeric(12,2) NOT NULL,
  currency       text NOT NULL DEFAULT 'BIF',
  status         text NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','success','failed','cancelled','refunded')),
  gateway        text,
  paid_at        timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pay_order ON public.payments(order_id);

CREATE TABLE IF NOT EXISTS public.reviews (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  rating      smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title       text,
  comment     text,
  is_approved boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (product_id, user_id)
);

-- ============================================================
-- NEWSLETTER — abonnés (formulaire footer du site)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email      text NOT NULL,
  phone      text,
  name       text,
  source     text NOT NULL DEFAULT 'footer',
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (email)
);

-- ============================================================
-- CONTACTS — messages du formulaire contact
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contacts (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  email      text NOT NULL,
  subject    text NOT NULL DEFAULT '',
  message    text NOT NULL,
  is_read    boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- VUES UTILES (dashboards admin)
-- ============================================================

-- Produits disponibles (stock réel > 0), avec image principale, tag, prix
CREATE OR REPLACE VIEW public.v_products_available AS
SELECT p.id, p.name, p.slug, p.reference, p.tag, p.price, p.old_price,
       p.rating, p.warranty, c.name AS category, b.name AS brand,
       (s.quantity - s.reserved_quantity) AS available_qty,
       pi.image_url AS main_image
FROM public.products p
LEFT JOIN public.categories c ON c.id = p.category_id
LEFT JOIN public.brands b ON b.id = p.brand_id
LEFT JOIN public.stock s ON s.product_id = p.id
LEFT JOIN LATERAL (
  SELECT image_url FROM public.product_images
  WHERE product_id = p.id ORDER BY sort_order LIMIT 1
) pi ON true
WHERE p.is_active AND (s.quantity - s.reserved_quantity) > 0;

-- Alerte stock faible / rupture
CREATE OR REPLACE VIEW public.v_low_stock AS
SELECT p.id, p.name, p.reference, s.quantity, s.reserved_quantity,
       (s.quantity - s.reserved_quantity) AS available,
       s.low_stock_threshold
FROM public.products p
JOIN public.stock s ON s.product_id = p.id
WHERE (s.quantity - s.reserved_quantity) <= s.low_stock_threshold;

-- Résumé des commandes par statut
CREATE OR REPLACE VIEW public.v_order_summary AS
SELECT status, COUNT(*) AS order_count, COALESCE(SUM(grand_total),0) AS total_amount
FROM public.orders
GROUP BY status;

-- Chiffre d'affaires total
CREATE OR REPLACE VIEW public.v_revenue AS
SELECT COALESCE(SUM(grand_total),0) AS total_revenue,
       COUNT(*) AS total_orders
FROM public.orders
WHERE status NOT IN ('cancelled','refunded');

-- Fiche produit complète (galerie, specs, certificat) pour produit.html
CREATE OR REPLACE VIEW public.v_product_full AS
SELECT p.*,
       c.name AS category, b.name AS brand,
       COALESCE(
         (SELECT jsonb_agg(jsonb_build_object('label',s.label,'value',s.value) ORDER BY s.sort_order)
          FROM public.product_specs s WHERE s.product_id = p.id), '[]'::jsonb) AS specs,
       COALESCE(
         (SELECT jsonb_agg(image_url ORDER BY sort_order)
          FROM public.product_images WHERE product_id = p.id), '[]'::jsonb) AS gallery,
       (SELECT jsonb_build_object('title', title, 'number', number, 'authority', authority,
                                 'cert_date', cert_date, 'points', points)
        FROM public.product_certificates c2 WHERE c2.product_id = p.id) AS cert,
       (SELECT quantity FROM public.stock WHERE product_id = p.id) AS stock
FROM public.products p
LEFT JOIN public.categories c ON c.id = p.category_id
LEFT JOIN public.brands b ON b.id = p.brand_id;

-- ============================================================
-- FONCTION : créer une commande (décrémente le stock)
-- ============================================================
CREATE OR REPLACE FUNCTION public.create_order(
  p_payment_method text,
  p_coupon_code text DEFAULT NULL,
  p_shipping_address_id uuid DEFAULT NULL,
  p_billing_address_id uuid DEFAULT NULL,
  p_notes text DEFAULT NULL
)
RETURNS TABLE(order_id uuid, order_number text, subtotal numeric, discount_total numeric, grand_total numeric)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cart_id        uuid;
  v_order_id       uuid;
  v_subtotal       numeric(12,2) := 0;
  v_discount       numeric(12,2) := 0;
  v_coupon_id      bigint;
  v_item           record;
  v_avail          integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Utilisateur non authentifié';
  END IF;

  SELECT id INTO v_cart_id FROM public.carts WHERE user_id = auth.uid();
  IF v_cart_id IS NULL THEN
    RAISE EXCEPTION 'Panier vide ou introuvable';
  END IF;

  IF p_coupon_code IS NOT NULL THEN
    SELECT ci.id, ci.discount_value
      INTO v_coupon_id, v_discount
    FROM public.coupons ci
    WHERE ci.code = p_coupon_code AND ci.is_active
      AND (ci.expires_at IS NULL OR ci.expires_at > now())
    LIMIT 1;
  END IF;

  INSERT INTO public.orders (order_number, user_id, coupon_id, payment_method,
                             shipping_address_id, billing_address_id, customer_notes)
  VALUES ('PS-' || to_char(now(),'YYYYMMDD') || '-' ||
          lpad((floor(random()*99999))::text, 5, '0'),
          auth.uid(), v_coupon_id, p_payment_method,
          p_shipping_address_id, p_billing_address_id, p_notes)
  RETURNING id INTO v_order_id;

  FOR v_item IN
    SELECT ci.product_id, ci.quantity, p.price
    FROM public.cart_items ci
    JOIN public.products p ON p.id = ci.product_id
    WHERE ci.cart_id = v_cart_id
  LOOP
    SELECT (quantity - reserved_quantity) INTO v_avail
    FROM public.stock WHERE product_id = v_item.product_id;

    IF v_avail IS NULL OR v_avail < v_item.quantity THEN
      RAISE EXCEPTION 'Stock insuffisant pour le produit %', v_item.product_id;
    END IF;

    INSERT INTO public.order_items (order_id, product_id, product_name, quantity,
                                    unit_price, subtotal)
    SELECT v_order_id, p.id, p.name, v_item.quantity, p.price, p.price * v_item.quantity
    FROM public.products p WHERE p.id = v_item.product_id;

    UPDATE public.stock SET quantity = quantity - v_item.quantity
    WHERE product_id = v_item.product_id;

    INSERT INTO public.stock_movements (product_id, user_id, quantity, movement_type, reference)
    VALUES (v_item.product_id, auth.uid(), -v_item.quantity, 'sale', v_order_id::text);

    v_subtotal := v_subtotal + (v_item.price * v_item.quantity);
  END LOOP;

  IF v_coupon_id IS NOT NULL AND v_discount > v_subtotal THEN
    v_discount := v_subtotal;
  END IF;

  UPDATE public.orders
  SET subtotal = v_subtotal,
      discount_total = v_discount,
      shipping_cost = 5000,
      grand_total = v_subtotal - v_discount + 5000
  WHERE id = v_order_id;

  INSERT INTO public.order_status_history (order_id, status, changed_by, note)
  VALUES (v_order_id, 'pending', auth.uid(), 'Commande créée');

  IF v_coupon_id IS NOT NULL THEN
    UPDATE public.coupons SET times_used = times_used + 1 WHERE id = v_coupon_id;
  END IF;

  DELETE FROM public.cart_items WHERE cart_id = v_cart_id;

  RETURN QUERY SELECT v_order_id,
    (SELECT o.order_number FROM public.orders o WHERE o.id = v_order_id),
    v_subtotal, v_discount, v_subtotal - v_discount + 5000;
END;
$$;

-- ============================================================
-- SÉCURITÉ AU NIVEAU DES LIGNES (RLS)
-- ============================================================
ALTER TABLE public.users        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlists    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_specs  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS users_self ON public.users;
CREATE POLICY users_self ON public.users
  FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Les administrateurs peuvent consulter l'ensemble des utilisateurs
-- (gestion des clients + jointures e-mail sur les commandes).
DROP POLICY IF EXISTS users_admin ON public.users;
CREATE POLICY users_admin ON public.users
  FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS addresses_self ON public.addresses;
CREATE POLICY addresses_self ON public.addresses
  FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS addresses_admin ON public.addresses;
CREATE POLICY addresses_admin ON public.addresses
  FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS carts_self ON public.carts;
CREATE POLICY carts_self ON public.carts
  FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS cart_items_self ON public.cart_items;
CREATE POLICY cart_items_self ON public.cart_items
  FOR ALL USING (cart_id IN (SELECT id FROM public.carts WHERE user_id = auth.uid()))
  WITH CHECK (cart_id IN (SELECT id FROM public.carts WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS wishlists_self ON public.wishlists;
CREATE POLICY wishlists_self ON public.wishlists
  FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS orders_self ON public.orders;
CREATE POLICY orders_self ON public.orders
  FOR SELECT USING (user_id = auth.uid() OR public.is_admin());
DROP POLICY IF EXISTS orders_insert ON public.orders;
CREATE POLICY orders_insert ON public.orders
  FOR INSERT WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS order_items_self ON public.order_items;
CREATE POLICY order_items_self ON public.order_items
  FOR SELECT USING (order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid() OR public.is_admin()));

DROP POLICY IF EXISTS payments_self ON public.payments;
CREATE POLICY payments_self ON public.payments
  FOR SELECT USING (order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid() OR public.is_admin()));

DROP POLICY IF EXISTS reviews_read ON public.reviews;
CREATE POLICY reviews_read ON public.reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS reviews_insert ON public.reviews;
CREATE POLICY reviews_insert ON public.reviews FOR INSERT
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS products_read ON public.products;
CREATE POLICY products_read   ON public.products   FOR SELECT USING (is_active);
DROP POLICY IF EXISTS products_write ON public.products;
CREATE POLICY products_write  ON public.products   FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS pimages_read ON public.product_images;
CREATE POLICY pimages_read  ON public.product_images FOR SELECT USING (true);
DROP POLICY IF EXISTS pimages_write ON public.product_images;
CREATE POLICY pimages_write ON public.product_images FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS specs_read ON public.product_specs;
CREATE POLICY specs_read  ON public.product_specs FOR SELECT USING (true);
DROP POLICY IF EXISTS specs_write ON public.product_specs;
CREATE POLICY specs_write ON public.product_specs FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS cert_read ON public.product_certificates;
CREATE POLICY cert_read  ON public.product_certificates FOR SELECT USING (true);
DROP POLICY IF EXISTS cert_write ON public.product_certificates;
CREATE POLICY cert_write ON public.product_certificates FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS categories_read ON public.categories;
CREATE POLICY categories_read ON public.categories FOR SELECT USING (true);
DROP POLICY IF EXISTS categories_write ON public.categories;
CREATE POLICY categories_write ON public.categories FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS brands_read ON public.brands;
CREATE POLICY brands_read ON public.brands FOR SELECT USING (true);
DROP POLICY IF EXISTS brands_write ON public.brands;
CREATE POLICY brands_write ON public.brands FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS stock_read ON public.stock;
CREATE POLICY stock_read  ON public.stock FOR SELECT USING (true);
DROP POLICY IF EXISTS stock_write ON public.stock;
CREATE POLICY stock_write ON public.stock FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS sm_read ON public.stock_movements;
CREATE POLICY sm_read  ON public.stock_movements FOR SELECT USING (public.is_admin());
DROP POLICY IF EXISTS sm_write ON public.stock_movements;
CREATE POLICY sm_write ON public.stock_movements FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS coupons_read ON public.coupons;
CREATE POLICY coupons_read ON public.coupons FOR SELECT USING (is_active);
DROP POLICY IF EXISTS coupons_write ON public.coupons;
CREATE POLICY coupons_write ON public.coupons FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS osh_read ON public.order_status_history;
CREATE POLICY osh_read ON public.order_status_history FOR SELECT
  USING (order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid() OR public.is_admin()));

-- Newsletter subscribers : tout le monde peut s'abonner (insert), admin gère tout
DROP POLICY IF EXISTS nsub_insert ON public.newsletter_subscribers;
CREATE POLICY nsub_insert ON public.newsletter_subscribers FOR INSERT
  WITH CHECK (true);
DROP POLICY IF EXISTS nsub_read ON public.newsletter_subscribers;
CREATE POLICY nsub_read ON public.newsletter_subscribers FOR SELECT
  USING (public.is_admin());
DROP POLICY IF EXISTS nsub_write ON public.newsletter_subscribers;
CREATE POLICY nsub_write ON public.newsletter_subscribers FOR ALL
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Contacts : tout le monde peut envoyer un message (insert), admin gère tout
DROP POLICY IF EXISTS contacts_insert ON public.contacts;
CREATE POLICY contacts_insert ON public.contacts FOR INSERT
  WITH CHECK (true);
DROP POLICY IF EXISTS contacts_read ON public.contacts;
CREATE POLICY contacts_read ON public.contacts FOR SELECT
  USING (public.is_admin());
DROP POLICY IF EXISTS contacts_write ON public.contacts;
CREATE POLICY contacts_write ON public.contacts FOR ALL
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ============================================================
-- EXÉCUTION DES FONCTIONS (rôles anon / authenticated)
-- create_order est SECURITY DEFINER : il tourne avec les droits du
-- propriétaire (contourne la RLS) mais vérifie auth.uid() en interne,
-- ce qui garantit qu'un utilisateur ne peut agir que sur SA commande.
-- ============================================================
GRANT EXECUTE ON FUNCTION public.create_order(text, text, uuid, uuid, text) TO anon, authenticated;

-- ------------------------------------------------------------
-- Admin : mise à jour du statut d'une commande
-- SECURITY DEFINER (contourne l'absence volontaire de policy UPDATE
-- sur orders) mais vérifie que l'appelant est bien administrateur.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_update_order_status(
  p_order_id uuid,
  p_status   text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Accès administrateur requis';
  END IF;
  IF p_status NOT IN ('pending','confirmed','processing','shipped','delivered','cancelled','refunded') THEN
    RAISE EXCEPTION 'Statut de commande invalide';
  END IF;
  UPDATE public.orders
     SET status = p_status, updated_at = now()
   WHERE id = p_order_id;
  INSERT INTO public.order_status_history (order_id, status, changed_by)
  VALUES (p_order_id, p_status, auth.uid());
END;
$$;
GRANT EXECUTE ON FUNCTION public.admin_update_order_status(uuid, text) TO anon, authenticated;

-- ============================================================
-- DONNÉES DE DÉMONSTRATION (alignées sur data.js + products.js)
-- ============================================================

-- Marques
INSERT INTO public.brands (name, slug) VALUES
('PixelStore','pixelstore'),('Dell','dell'),('HP','hp'),('Logitech','logitech'),
('Razer','razer'),('Samsung','samsung'),('Sony','sony')
ON CONFLICT (slug) DO NOTHING;

-- Catégories (catalogue frontend)
INSERT INTO public.categories (name, slug) VALUES
('Ordinateurs','ordinateurs'),('Claviers','claviers'),('Souris','souris'),
('Écrans','ecrans'),('Casques','casques'),('Composants','composants')
ON CONFLICT (slug) DO NOTHING;

-- Produits « maison » PixelStore (data.js, ids 1-12)
INSERT INTO public.products
  (id, name, slug, reference, brand_id, category_id, tag, description, price, old_price, rating, rating_count, warranty)
SELECT d.id, d.name, d.slug, d.reference, b.id, c.id, d.tag, d."desc", d.price, d.old_price, d.rating, d.rating_count, d.warranty
FROM (VALUES
  (1::bigint,'OrdiPro Pixel X15','ordipro-pixel-x15','ORD-PX-X15','PixelStore','ordinateurs','Nouveau',
   'L''ultrabook signature de PixelStore : puissance, finesse et autonomie.',850000.00,950000.00,4.8::numeric,1,'2 ans'),
  (2,'Clavier MécaK Pixel K68','clavier-mecak-pixel-k68','CLV-K68-RGB','PixelStore','claviers','Top vente',
   'Un clavier mécanique compact aux switchs tactiles.',65000.00,85000.00,4.7,1,'1 an'),
  (3,'PixelMouse Pro','pixelmouse-pro','SOU-PX-PRO','PixelStore','souris','Nouveau',
   'Notre souris gaming référence : capteur haute précision.',45000.00,58000.00,4.6,1,'2 ans'),
  (4,'Écran UltraPixel 27''''','ecran-ultrapixel-27','ECR-UP-27K','PixelStore','ecrans','4K Ultra HD',
   'Un moniteur 4K aux couleurs ultra-fidèles.',320000.00,380000.00,4.9,1,'2 ans'),
  (5,'Casque PixelSound H90','casque-pixelsound-h90','CSQ-PS-H90','PixelStore','casques','Son immersif',
   'Un casque surround à réduction de bruit active.',95000.00,110000.00,4.7,1,'1 an'),
  (6,'SSD PixelStore 1To NVMe','ssd-pixelstore-1to-nvme','SSD-PX-1TB','PixelStore','composants','Performance',
   'Un SSD ultra-rapide pour des chargements instantanés.',55000.00,65000.00,4.8,1,'5 ans'),
  (7,'PixelBook 14','pixelbook-14','PC-PB-14','PixelStore','ordinateurs','Ultra mobile',
   'Un ultrabook léger et endurant, pensé pour la mobilité.',720000.00,800000.00,4.6,1,'2 ans'),
  (8,'Clavier PixelK Air 75','clavier-pixelk-air-75','CLV-K75-AIR','PixelStore','claviers','Confort',
   'Un clavier compact 75% au châssis fin.',78000.00,90000.00,4.5,1,'1 an'),
  (9,'Souris PixelEase','souris-pixelease','SOU-PX-EASE','PixelStore','souris','Confort',
   'Une souris silencieuse et légère pour un confort durable.',28000.00,35000.00,4.4,1,'1 an'),
  (10,'Écran VisionPixel 24''''','ecran-visionpixel-24','ECR-VP-24F','PixelStore','ecrans','Essentiel',
   'Un écran FHD polyvalent au suivi fluide.',145000.00,175000.00,4.5,1,'2 ans'),
  (11,'Casque PixelStudio','casque-pixelstudio','CSQ-PS-STUDIO','PixelStore','casques','Créateurs',
   'Un casque Hi-Fi à réduction de bruit hybride.',120000.00,140000.00,4.8,1,'2 ans'),
  (12,'PixelGPU RTX 4070','pixelgpu-rtx-4070','GPU-PX-4070','PixelStore','composants','Puissance',
   'La carte graphique nouvelle génération pour du gaming 1440p-4K.',620000.00,680000.00,4.9,1,'3 ans')
) AS d(id, name, slug, reference, brand_name, category_slug, tag, "desc", price, old_price, rating, rating_count, warranty)
JOIN public.brands b ON b.name = d.brand_name
JOIN public.categories c ON c.slug = d.category_slug
ON CONFLICT (id) DO NOTHING;

-- Corrige la catégorie des produits déjà présents (ajouté après coup) :
-- affecte category_id d'après le slug de la catégorie correspondante.
UPDATE public.products p
SET category_id = c.id
FROM public.categories c
WHERE p.category_id IS NULL
  AND (p.id IN (1,7) AND c.slug = 'ordinateurs' OR
       p.id IN (2,8) AND c.slug = 'claviers' OR
       p.id IN (3,9) AND c.slug = 'souris' OR
       p.id IN (4,10) AND c.slug = 'ecrans' OR
       p.id IN (5,11) AND c.slug = 'casques' OR
       p.id IN (6,12) AND c.slug = 'composants');

-- Galerie d'images (alignée sur data.js : product.gallery)
-- On purge d'abord les images de ces produits pour rendre le script ré-exécutable.
DELETE FROM public.product_images WHERE product_id IN (1,2,3,4,5,6,7,8,9,10,11,12);
INSERT INTO public.product_images (product_id, image_url, sort_order, is_main)
SELECT p.id, g.image_url, g.sort_order, g.is_main
FROM (VALUES
  (1::bigint,'img/products/1496181133206-80ce9b88a853.jpg',0,true),
  (1,'img/products/1531297484001-80022131f5a1.jpg',1,false),
  (1,'img/products/1504639725590-34d0984388bd.jpg',2,false),
  (2,'img/products/1587829741301-dc798b83add3.jpg',0,true),
  (2,'img/products/1618384887929-16ec33fab9ef.jpg',1,false),
  (2,'img/products/1595225476474-87563907a212.jpg',2,false),
  (3,'img/products/1527864550417-7fd91fc51a46.jpg',0,true),
  (3,'img/products/1615663245857-ac93bb7c39e7.jpg',1,false),
  (3,'img/products/1592899677977-9c10ca588bbd.jpg',2,false),
  (4,'img/products/1527443224154-c4a3942d3acf.jpg',0,true),
  (4,'img/products/1547082299-de196ea013d6.jpg',1,false),
  (4,'img/products/1585792180666-f7347c490ee2.jpg',2,false),
  (5,'img/products/1505740420928-5e560c06d30e.jpg',0,true),
  (5,'img/products/1546435770-a3e426bf472b.jpg',1,false),
  (5,'img/products/1583394838336-acd977736f90.jpg',2,false),
  (6,'img/products/1591370874773-6702e8f12fd8.jpg',0,true),
  (6,'img/products/1600267185393-e158a98703de.jpg',1,false),
  (6,'img/products/1563770660941-20978e870e26.jpg',2,false),
  (7,'img/products/1517336714731-489689fd1ca8.jpg',0,true),
  (7,'img/products/1531297484001-80022131f5a1.jpg',1,false),
  (7,'img/products/1504639725590-34d0984388bd.jpg',2,false),
  (8,'img/products/1618384887929-16ec33fab9ef.jpg',0,true),
  (8,'img/products/1595225476474-87563907a212.jpg',1,false),
  (8,'img/products/1541140532154-b024d705b90a.jpg',2,false),
  (9,'img/products/1615663245857-ac93bb7c39e7.jpg',0,true),
  (9,'img/products/1527864550417-7fd91fc51a46.jpg',1,false),
  (9,'img/products/1592899677977-9c10ca588bbd.jpg',2,false),
  (10,'img/products/1551645120-d70bfe84c826.jpg',0,true),
  (10,'img/products/1527443224154-c4a3942d3acf.jpg',1,false),
  (10,'img/products/1547082299-de196ea013d6.jpg',2,false),
  (11,'img/products/1546435770-a3e426bf472b.jpg',0,true),
  (11,'img/products/1583394838336-acd977736f90.jpg',1,false),
  (11,'img/products/1484704849700-f032a568e944.jpg',2,false),
  (12,'img/products/1591488320449-011701bb6704.jpg',0,true),
  (12,'img/products/1587202372634-32705e3bf49c.jpg',1,false),
  (12,'img/products/1591799264318-7e6ef8ddb7ea.jpg',2,false)
) AS g(pid, image_url, sort_order, is_main)
JOIN public.products p ON p.id = g.pid;

-- Caractéristiques techniques (alignées sur data.js : product.specs)
INSERT INTO public.product_specs (product_id, label, value, sort_order)
SELECT p.id, s.label, s.value, s.sort_order
FROM (VALUES
  (1::bigint,'Processeur','Intel Core i7-13700H',1),
  (1,'Mémoire RAM','16 Go DDR5',2),(1,'Stockage','SSD NVMe 1 To',3),
  (1,'Écran','15,6'''' FHD 144 Hz',4),(1,'Carte graphique','RTX 4060 8 Go',5),
  (1,'Système d''exploitation','Windows 11 Pro',6),(1,'Connectique','USB-C, HDMI 2.1, Jack 3,5 mm',7),
  (1,'Autonomie','Jusqu''à 12 h',8),
  (2,'Format','68 touches (65%)',1),(2,'Switchs','Mécaniques rouges',2),
  (2,'Rétroéclairage','RGB par touche',3),(2,'Connexion','USB-C / 2.4 GHz',4),
  (2,'Matériaux','Châssis aluminium',5),(2,'Touches','PBT double injection',6),
  (2,'Anti-ghosting','NKRO plein clavier',7),
  (3,'Capteur','25 600 DPI',1),(3,'Boutons','8 programmables',2),(3,'Taux de rapport','1000 Hz',3),
  (3,'Connexion','Sans fil 2.4 GHz',4),(3,'Poids','58 g',5),(3,'Autonomie','70 h',6),
  (3,'Compatibilité','Windows, macOS, Linux',7),
  (4,'Dalle','IPS 27 pouces',1),(4,'Résolution','4K UHD 3840x2160',2),(4,'Taux de rafraîch.','120 Hz',3),
  (4,'Colorimétrie','100% sRGB',4),(4,'Connectique','HDMI 2.1, DisplayPort',5),(4,'HDR','HDR400',6),
  (4,'Angle de vue','178° / 178°',7),
  (5,'Transducteurs','50 mm',1),(5,'Réduction bruit','ANC active',2),(5,'Son','Surround 7.1 virtuel',3),
  (5,'Micro','Amovible antibruit',4),(5,'Connexion','USB / Sans fil',5),(5,'Autonomie','40 h',6),
  (5,'Poids','320 g',7),
  (6,'Capacité','1 To',1),(6,'Interface','NVMe PCIe 4.0',2),(6,'Lecture','7 300 Mo/s',3),
  (6,'Écriture','6 800 Mo/s',4),(6,'Format','M.2 2280',5),(6,'Endurance','600 TBW',6),
  (6,'Garantie','5 ans',7),
  (7,'Processeur','Intel Core i5-1340P',1),(7,'Mémoire RAM','16 Go LPDDR5',2),
  (7,'Stockage','SSD NVMe 512 Go',3),(7,'Écran','14'''' 2.8K OLED',4),(7,'Poids','1,2 kg',5),
  (7,'Autonomie','Jusqu''à 14 h',6),(7,'Système d''exploitation','Windows 11 Pro',7),
  (8,'Format','75% (82 touches)',1),(8,'Switchs','Mécaniques bruns',2),(8,'Hot-swap','Compatible 3/5 broches',3),
  (8,'Rétroéclairage','RGB 16,8 M',4),(8,'Connexion','Bluetooth / 2.4 GHz / USB-C',5),
  (8,'Multi-appareils','Jusqu''à 3 appareils',6),(8,'Touches','PBT double injection',7),
  (9,'Capteur','12 000 DPI',1),(9,'Boutons','6 programmables',2),(9,'Clics','Silencieux',3),
  (9,'Connexion','Sans fil 2.4 GHz',4),(9,'Poids','75 g',5),(9,'Autonomie','Jusqu''à 90 h',6),
  (9,'Recharge','USB-C',7),
  (10,'Dalle','IPS 24 pouces',1),(10,'Résolution','FHD 1920x1080',2),(10,'Taux de rafraîch.','100 Hz',3),
  (10,'Colorimétrie','99% sRGB',4),(10,'Connectique','HDMI, DisplayPort',5),
  (10,'Protection','Anti-lumière bleue',6),(10,'Angle de vue','178° / 178°',7),
  (11,'Transducteurs','45 mm Hi-Fi',1),(11,'Réduction bruit','ANC hybride',2),(11,'Son','Audio haute résolution',3),
  (11,'Micro','Studio intégré',4),(11,'Connexion','Bluetooth 5.3 / Jack',5),(11,'Autonomie','45 h',6),
  (11,'Recharge','USB-C',7),
  (12,'GPU','NVIDIA GeForce RTX 4070',1),(12,'Mémoire','12 Go GDDR6X',2),(12,'Cœurs CUDA','5 888',3),
  (12,'Fréquence boost','2,5 GHz',4),(12,'Refroidissement','Triple ventilateur',5),(12,'TGP','200 W',6),
  (12,'Connectique','HDMI 2.1, DisplayPort 1.4a',7)
) AS s(pid, label, value, sort_order)
JOIN public.products p ON p.id = s.pid
ON CONFLICT (product_id, label) DO NOTHING;

-- Certificats de conformité (alignés sur data.js : product.cert)
INSERT INTO public.product_certificates (product_id, title, number, authority, cert_date, points)
SELECT p.id, crt.title, crt.number, crt.authority, crt.cert_date::date, crt.points
FROM (VALUES
  (1::bigint,'Certificat de conformité CE','PC-2026-0015','Bureau Burundais de Normalisation (BBN)','2026-06-12',
   '["Conforme aux exigences essentielles de la directive CEM 2014/30/UE","Certifié RoHS : fabrication sans substances dangereuses","Sécurité électrique selon la norme CEI 62368-1"]'::jsonb),
  (2,'Certificat de conformité CEM','PC-2026-0032','Bureau Burundais de Normalisation (BBN)','2026-04-03',
   '["Conforme à la directive CEM 2014/30/UE","Certifié RoHS : matériaux sans plomb","Clavier usé et testé 1 000 000 de frappes"]'::jsonb),
  (3,'Certificat de conformité CE','PC-2026-0041','Bureau Burundais de Normalisation (BBN)','2026-05-21',
   '["Conforme à la directive basse tension 2014/35/UE","Certifié RoHS et REACH","Testée à 150 millions de clics"]'::jsonb),
  (4,'Certificat de conformité sécurité','PC-2026-0058','Bureau Burundais de Normalisation (BBN)','2026-02-09',
   '["Conforme à la norme CEI 62368-1 (sécurité électrique)","Certifié TÜV (filtre de lumière bleue, anti-scintillement)","Respecte la directive EEE 2012/19/UE (recyclage)"]'::jsonb),
  (5,'Certificat de conformité acoustique','PC-2026-0069','Bureau Burundais de Normalisation (BBN)','2026-03-17',
   '["Conforme à la directive CEM 2014/30/UE","Limitation du niveau sonore (norme EN 50332)","Certifié RoHS pour les composants électroniques"]'::jsonb),
  (6,'Certificat de conformité CE','PC-2026-0081','Bureau Burundais de Normalisation (BBN)','2026-05-28',
   '["Conforme à la directive CEM 2014/30/UE","Certifié RoHS : sans plomb ni cadmium","Endurance testée (600 TBW)"]'::jsonb),
  (7,'Certificat de conformité CE','PC-2026-0094','Bureau Burundais de Normalisation (BBN)','2026-07-14',
   '["Conforme à la directive CEM 2014/30/UE","Certifié RoHS : fabrication sans substances dangereuses","Sécurité électrique selon la norme CEI 62368-1"]'::jsonb),
  (8,'Certificat de conformité CEM','PC-2026-0102','Bureau Burundais de Normalisation (BBN)','2026-07-22',
   '["Conforme à la directive CEM 2014/30/UE","Certifié RoHS : matériaux sans plomb","Switchs testés à 70 millions de frappes"]'::jsonb),
  (9,'Certificat de conformité CE','PC-2026-0111','Bureau Burundais de Normalisation (BBN)','2026-08-05',
   '["Conforme à la directive basse tension 2014/35/UE","Certifié RoHS : sans plomb ni mercure","Clics testés à 50 millions d''opérations"]'::jsonb),
  (10,'Certificat de conformité sécurité','PC-2026-0120','Bureau Burundais de Normalisation (BBN)','2026-08-19',
   '["Conforme à la norme CEI 62368-1 (sécurité électrique)","Certifié TÜV (filtre de lumière bleue)","Respecte la directive EEE 2012/19/UE (recyclage)"]'::jsonb),
  (11,'Certificat de conformité acoustique','PC-2026-0129','Bureau Burundais de Normalisation (BBN)','2026-06-10',
   '["Conforme à la directive CEM 2014/30/UE","Limitation du niveau sonore (norme EN 50332)","Certifié RoHS pour les composants électroniques"]'::jsonb),
  (12,'Certificat de conformité CE','PC-2026-0138','Bureau Burundais de Normalisation (BBN)','2026-08-27',
   '["Conforme à la directive CEM 2014/30/UE","Certifié RoHS : sans plomb ni cadmium","Alimentation conforme EN 62368-1"]'::jsonb)
) AS crt(pid, title, number, authority, cert_date, points)
JOIN public.products p ON p.id = crt.pid
ON CONFLICT (product_id) DO NOTHING;

-- Stocks (alignés sur data.js : stock des produits PixelStore)
INSERT INTO public.stock (product_id, quantity, low_stock_threshold)
SELECT p.id, sv.qty, 5
FROM (VALUES
  (1::bigint,8),(2,15),(3,20),(4,6),(5,12),(6,30),
  (7,10),(8,22),(9,18),(10,14),(11,7),(12,4)
) AS sv(pid, qty)
JOIN public.products p ON p.id = sv.pid
ON CONFLICT (product_id) DO NOTHING;

-- Coupon de démo
INSERT INTO public.coupons (code, discount_type, discount_value, is_active)
VALUES ('BIENVENUE10', 'percentage', 10, true)
ON CONFLICT (code) DO NOTHING;

-- Promotion admin : remonte les comptes existants dont l'email correspond
-- à l'email administrateur fixe. Idempotent (ne modifie que les lignes utiles).
UPDATE public.users
   SET role = 'admin'
 WHERE lower(email) = lower('admin@pixelstore.bi');

-- Réinitialise la séquence d'identité de products. Les seeds ci-dessus insèrent
-- avec des id EXPLICITES (1..12) : la séquence ne progresse pas, et le prochain
-- insertion SANS id repartirait de 1 → violation de clé primaire (products_pkey).
-- Cette ligne remet la séquence au-dessus du max actuel, ce qui la corrige.
SELECT setval('products_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.products), 1));

-- ============================================================
-- IMAGES PRODUITS — stratégie retenue (compression côté client)
-- Les images sont redimensionnées et compressées dans le navigateur
-- (canvas → JPEG, max ~1000 px, qualité auto) avant d'être stockées en
-- data URI léger (~100-200 Ko) dans product_images.image_url.
-- Aucun Storage ni téléversement de fichiers : seule une petite chaîne
-- base64 voyage, ce qui évite la lenteur des anciens data URI de plusieurs Mo.
-- → Les listings (admin + boutique) ne chargent JAMAIS les data URI
--   (filtrés par NOT ILIKE 'data:%' côté REST) : seuls les chemins légers
--   img/... et le produit consulté passent, ce qui garde les pages rapides.
-- ============================================================
